version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT
    volumes:
      - ./db:/data/db
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  server:
    ports:
      - 4001:4001
    image: maccabeus/url-shortener-server:latest
    depends_on:
      - mongodb

  app:
    ports:
      - 3000:3000
    image: maccabeus/url-shortener-app:latest
    depends_on:
      - server
